name: PR-CI
# trigger specification
on:
  pull_request:
    branches:
      - '*'
# job specification
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set-up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test
        run: ./gradlew -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false --no-daemon --no-parallel --continue test --stacktrace